### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by Yacovitch** [QWTforGithub/PUDM#13]
Hi there,

I noticed that in your configuration, max_epoch is set to 2000. Is this the setting you used during training? Additionally, could you please share how long the training process took using an RTX 3090?

Thanks in advance for your help!

**Comment by QWTforGithub** [comment]
Hi, in our paper, we trained PUDM for 1000 epochs on PUGAN (about 20000 samples). This took about 5 days on an NVIDIA 3090 GPU. However, we found that this did not actually converge completely, as qualitative results became better as training continued. I recommend training PUDM for 1000 epochs. This codebase has another flaw, such as not selecting the best CD result. Therefore, we plan to release a better version, PUDM v2, in the future.

Best wish for you.

**Comment by QWTforGithub** [comment]
Hi, on PU1K, about 300 epochs are enough to achieve the desired effect.

**Comment by QWTforGithub** [comment]
I'm sorry, this is a issue in the code. I didn't point to the best CD loss during training. I think you can add it during training.I tested the checkpoints one by one after the training was completed. Or, you can do what I did and test multiple checkpoints.

**Comment by QWTforGithub** [comment]
Hi, thank you for your attention. I need to retrain PUDM. I'm meeting a deadline lately. After I finish that, I'll focus on fixing this code.

**Comment by QWTforGithub** [comment]
By the way, I think you can write a loop code to find the best checkpoint. It won't take much time.
