### ISSUE TITLE
训练结果不均匀情况

### ISSUE THREAD

**Issue by AbaAbaAbaX** [QWTforGithub/PUDM#16]
作者您好，首先对您的作品表示感谢。我在尝试生成更高上采样率的模型时遇到了如下问题，想请教您：
使用ModelNet40中的bottle_0430进行数据准备和生成后，出现了点云不均匀的情况，大致形状如下：
![image](https://github.com/user-attachments/assets/c252e7b5-c984-4bbc-ab42-f331a991c341)
使用示例的pig.xyz进行16倍上采样时，结果也出现了不均匀的情况，但效果优于bottle：
![image](https://github.com/user-attachments/assets/6a1192c1-cb5f-49dd-8a8f-9bb85e29e6cd)
想请教一下出现这种情况是由于我本地的设置问题，还是由扩散模型训练数据集的特点导致的。
对应的生成结果在压缩包中
[generated_results.zip](https://github.com/user-attachments/files/17916810/generated_results.zip)

**Comment by QWTforGithub** [comment]
请问，你的点云数据是来自ModelNet40中训练集还是测试集呢，是哪个下标呢？我再尝试一下。

**Comment by QWTforGithub** [comment]
你好，我找到你说的点云了：
![image](https://github.com/user-attachments/assets/8e818556-9b5a-45bc-83b7-f80f8e58636c)
4倍上采样：
![image](https://github.com/user-attachments/assets/378406d8-d73f-4168-9cfd-f2d38184f2c4)
16倍上采样：
![image](https://github.com/user-attachments/assets/eed9eecb-7d1a-4e58-b1a3-59266f076990)
在我的环境下，我没有得到那么差的结果。运行的命令如下：
python example_samples.py --dataset PUGAN --R 16 --step 30 --example_file ./example/example.xyz

**Comment by AbaAbaAbaX** [comment]
感谢您的及时回复，应该是我环境配置上的问题。通过下载pytorch3d包并使用conda安装，会在我的环境中显示找不到pytorch3d模块，我是先配置了pytorch3d环境，在此基础上配置的本项目环境，不清楚是否会有影响。另外我是在windows系统中配置的环境，anaconda官方和本项目网盘中的pytorch3d包似乎都是linux平台的，是否只能自行配置pytorch3d，而无法直接使用压缩包安装?以下是直接使用下载的安装包进行配置的环境情况（过程中pointops中的grouping_int报错并提示error LNK2001: [无法解析的外部符号]，我对其进行了修改，主要是将long int替换为int64_t，然后compile通过，不知道是否有影响）：
$ conda list

# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
black                     23.3.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
ca-certificates           2024.9.24            haa95532_0    defaults
cachetools                5.5.0                    pypi_0    pypi
certifi                   2022.12.7        py37haa95532_0    defaults
cffi                      1.15.1                   pypi_0    pypi
chamfer-3d                0.0.0                    pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
cudatoolkit               11.8.0               hd77b12b_0    defaults
cycler                    0.11.0                   pypi_0    pypi
dash                      2.15.0                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.7.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
flake8                    5.0.4                    pypi_0    pypi
flask                     2.2.5                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
google-auth               2.36.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.62.3                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
hydra-core                0.11.3                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
json5                     0.9.16                   pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.1.1                    pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
jupyter-server            1.24.0                   pypi_0    pypi
jupyterlab                3.5.3                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.15.2                   pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
libcst                    1.0.1                    pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
markdown                  3.1                      pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
moreorless                0.4.0                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclassic                 1.1.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.6.0                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.5.7                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
nvidia-cublas-cu11        11.11.3.6                pypi_0    pypi
nvidia-cudnn-cu11         9.5.1.17                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 1.4.1                    pypi_0    pypi
open3d                    0.17.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   3.0.15               h827c3e9_0    defaults
packaging                 24.0                     pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37haa95532_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.0.0                    pypi_0    pypi
plotly                    5.18.0                   pypi_0    pypi
pointnet2                 3.0.0                    pypi_0    pypi
pointnet2-ops             3.0.0                    pypi_0    pypi
pointops                  0.0.0                    pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycodestyle               2.9.1                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  2.5.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.7.1                h33f27b4_4    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         0.7.1                    pypi_0    pypi
pytorch3d                 0.6.1           py37_cu111_pyt191    <unknown>
pytz                      2024.2                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   308                      pypi_0    pypi
pywinpty                  2.0.10                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                65.6.3           py37haa95532_0    defaults
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
stdlibs                   2022.10.9                pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     1.9.1+cu111              pypi_0    pypi
torchaudio                0.9.1                    pypi_0    pypi
torchvision               0.10.1+cu111             pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
trailrunner               1.4.0                    pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.5.5                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
usort                     1.0.8.post1              pypi_0    pypi
vc                        14.40                h2eaa2aa_1    defaults
vs2015_runtime            14.40.33807          h98bb1dd_1    defaults
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37haa95532_0    defaults
widgetsnbextension        4.0.13                   pypi_0    pypi
wincertstore              0.2              py37haa95532_2    defaults
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi

此时运行python example_samples.py --dataset PUGAN --R 128 --step 30 --example_file ./example/pig.xyz会报错，提示：
Traceback (most recent call last):
  File "example_samples.py", line 8, in <module>
    from models.pointnet2_with_pcld_condition import PointNet2CloudCondition
  File "D:\tyh\projects\EveryThing\PUDM-main\pointnet2\models\__init__.py", line 2, in <module>
    from pointnet2.models.pointnet2_ssg_sem import PointNet2SemSegSSG
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2-3.0.0-py3.7.egg\pointnet2\__init__.py", line 1, in <module>
    from pointnet2 import models
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2-3.0.0-py3.7.egg\pointnet2\models\__init__.py", line 2, in <module>
    from pointnet2.models.pointnet2_ssg_sem import PointNet2SemSegSSG
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2-3.0.0-py3.7.egg\pointnet2\models\pointnet2_ssg_sem.py", line 3, in <module>
    from pointnet2_ops.pointnet2_modules import PointnetFPModule, PointnetSAModule, PointnetKnnFPModule
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2_ops-3.0.0-py3.7-win-amd64.egg\pointnet2_ops\__init__.py", line 1, in <module>
    import pointnet2_ops.pointnet2_modules
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2_ops-3.0.0-py3.7-win-amd64.egg\pointnet2_ops\pointnet2_modules.py", line 6, in <module>
    from pointnet2_ops import pointnet2_utils
  File "D:\Anaconda\envs\PUDM-main\lib\site-packages\pointnet2_ops-3.0.0-py3.7-win-amd64.egg\pointnet2_ops\pointnet2_utils.py", line 7, in <module>
    from pytorch3d.ops import knn
ModuleNotFoundError: No module named 'pytorch3d'

**Comment by AbaAbaAbaX** [comment]
另外可以麻烦您尝试对bottle_0430进行128倍上采样来看一下效果吗，很抱歉我没有在第一次提问的时候说清楚，效果较差的bottle_0430是进行128倍上采样的结果。我重新进行了配置，得到16倍结果：
![image](https://github.com/user-attachments/assets/d6798681-6ebd-4b20-80d3-b0614d07304c)
128倍结果：
![image](https://github.com/user-attachments/assets/9149075f-380e-4efc-8854-7d830eaba6ba)
目前看来发散的情况有所好转，空洞应该是不可避免

**Comment by QWTforGithub** [comment]
这是在我的环境下进行128倍上采样的结果。我建议还是在linux下配置PUDM，目前看来在Windows下pytorch3d没有安装好（在PUDM-main/pointnet2/models/pointnet2_with_pcld_condition.py应用了一个pytroch3d中的knn函数，或者你可以使用其他的knn函数代替它）。
![image](https://github.com/user-attachments/assets/3f325e46-04a4-4b8a-810d-25d2cf163c0e)

**Comment by QWTforGithub** [comment]
不客气。
