### ISSUE TITLE
Question about predicted noise.

### ISSUE THREAD

**Issue by gyjung975** [QWTforGithub/PUDM#17]
Hi, thank you for your great work!

I have a question about predicted noise during training.

https://github.com/QWTforGithub/PUDM/blob/623649a61d2d2e218b50ec120eb6a31274621144/pointnet2/models/pointnet2_with_pcld_condition.py#L620-L621

Isn't `out` on line 620 the predicted noise?
It is `out` on line 621 that is calculating mse_loss with `z` from `std_normal`.
I would be grateful if you could explain line 621.

Thank you.

**Comment by QWTforGithub** [comment]
Thank you for your attention to our work. In fact, you can find that during inference, we predict the result is $$x_t+i$$, not $x_t$. This is to convert $$\epsilon+i$$ during training to $$f(\epsilon)+i$$. Of course, I found that directly predicting the noise $$\epsilon$$ during training can also generate great results. In future versions, I will correct this implementation problem. Thank you very much for pointing out this problem.

**Comment by gyjung975** [comment]
I didn't check the inference process. Now I understand.
Thank you for your quick reply.
