### ISSUE TITLE
关于模型对带有噪声点云数据的处理能力

### ISSUE THREAD

**Issue by AbaAbaAbaX** [QWTforGithub/PUDM#18]
您好，再次对您的作品表示感谢。我在使用扩散模型的时候注意到，模型对于无噪声点云的补全能力很好，但在处理带有噪声的点云数据时（例如example文件夹中的如下文件：
![image](https://github.com/user-attachments/assets/dc861d3f-47ba-45c5-bf2b-e9cd719fcb07)
会把噪声作为条件的一部分进行补全，我运行python .\example_samples.py --dataset PUGAN --R 16 --step 30 --example_file ./example/pig_random_noise_0.1.xyz得到结果如下：
![image](https://github.com/user-attachments/assets/6f2191c0-88a3-4a5d-bbbd-166ac8a21bb1)
表面情况与无噪声点云的扩散结果有不小的差距，想请教一下这种情况是否正常？以及是否可以通过某些方式改善？

**Comment by QWTforGithub** [comment]
你好，你生成的结果和我的是差不多的，这是正常的。PUDM本身是个点云上采样的方法，并不是点云去噪方法，也仅仅是相对于其他的上采样方法对噪声更鲁棒。我的建议是，利用专门的点云去噪方法来尝试处理之后，再进行上采样。这里，我建议如下的去噪方法（也是基于DDPMs的，可以找其他的方法也可以）：
https://p2p-bridge.github.io/
可以尝试一下，先对点云去噪，再次上采样。

**Comment by AbaAbaAbaX** [comment]
好的好的，感谢！

**Comment by QWTforGithub** [comment]
不客气。
