### ISSUE TITLE
Can only run on NVIDIA 3090 GPU

### ISSUE THREAD

**Issue by Yiyao-Ma** [QWTforGithub/PUDM#19]
Hi! Thank you for your excellent work. I've discovered that the environment can only run on an **NVIDIA 3090 GPU** and will encounter errors such as `CUDA kernel failed: no kernel image is available for execution on the device` within the `pointnet2_ops` package. I am curious about why this exists and where you specify the GPU version in the code.

**Comment by QWTforGithub** [comment]
Thanks for your attention to our work. PUDM can run not only on NVIDIA 3090 GPU, but also on other GPUs (4090, A40). I think it is likely that pointnet2_ops is not installed properly. For this question, please refer to # 14. I can give you two environment references:
1. CUDA 11.6, g++/gcc 7.5.0
2. CUDA 11.8 g++/gcc 11.4.0
I can successfully configure PUDM in the above environments.

**Comment by Yiyao-Ma** [comment]
Thanks for your reply! I've tried on Ubuntu 22.04, gcc 11.4.0, CUDA 11.8, torch 2.0.0, with NVIDIA A100 GPU, but still has the previous problems. Could you provide more detail about the CUDA 11.8 gcc 11.4.0 environment? Thanks in advance!

**Comment by QWTforGithub** [comment]
Hi, I reconfigured PUDM according to the readme and found no problems.
![image](https://github.com/user-attachments/assets/228f9c7a-8df7-4b7f-bfee-9bc2c8cbc21b)

I think you can install it strictly according to the readme. In my environment, I am not using torch2.0.0, but torch1.9.1.
For specific installation steps, please refer to readme or #14 .

**Comment by QWTforGithub** [comment]
![image](https://github.com/user-attachments/assets/75dd9791-0672-4bf9-a8ad-80b957330400)

**Comment by Yiyao-Ma** [comment]
Thanks for your reply! It is very wired, I also tried to install the environment strictly following your readme. It works on the 3090 but fails on other GPUs. Regardless, I will use 3090 to run it :)
<img width="855" alt="Screenshot 2024-12-10 at 08 17 21" src="https://github.com/user-attachments/assets/918e93b4-ea2c-41d8-a16d-88965e8b8e27">

**Comment by QWTforGithub** [comment]
Perhaps this is because the installation lacks some underlying dependencies of Linux? Please run the code to check whether pytorch can run normally:

import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.backends.cudnn.version())
print(torch.version.cuda)
 
The code should be GPU-independent.
