### ISSUE TITLE
pointnet2编译

### ISSUE THREAD

**Issue by Philcalab** [QWTforGithub/PUDM#4]
你好，我看到你提供的代码中已经有pointnet2相关代码，请问在复现代码时是否可以不用再下载pointnet2代码，直接执行 sh compile.sh就可以呢？

**Comment by QWTforGithub** [comment]
是的。但是，需要提前安装相关的依赖包，不然会编译失败。因此，我才提供了pointnet2的网址。

**Comment by Philcalab** [comment]
好的，感谢～

**Comment by QWTforGithub** [comment]
不客气。
