### ISSUE TITLE
关于环境配置

### ISSUE THREAD

**Issue by USTBcvpaperreading** [QWTforGithub/PUDM#5]
请问您在环境配置中的这两行是什么意思呢？

 install pointnet2
https://github.com/erikwijmans/Pointnet2_PyTorch/tree/master
另问： 您是否有安装 pytorch3d 这个包呢，可否告知一下版本？我在进行 example_sample.py的时候，提示我没有 pytorch3d 这个包。

**Comment by QWTforGithub** [comment]
安装pointnet2的环境需要遵循该网站。抱歉，疏忽了pytorch3d的安装，后续我会更新read.me。请根据如下方式安装pytorch3d
**1. 安装如下包：https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
scikit-image
black
usort
flake8
matplotlib
tdqm
jupyter
imageio
fvcore
plotly
opencv-python
2. 下载对应pytorch3d版本：https://anaconda.org/pytorch3d/pytorch3d/files?page=10
我安装的版本：conda install pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2**

**Comment by QWTforGithub** [comment]
可以说一下是哪个文件报没有pytorch3d的吗？

**Comment by USTBcvpaperreading** [comment]
> 安装pointnet2的环境需要遵循该网站。 抱歉，疏忽了pytorch3d的安装，后续我会更新readme。另外，可以说一下是哪个文件报没有pytorch3d的吗？ 请根据如下方式安装pytorch3d **1. 安装如下包：https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md scikit-image black usort flake8 matplotlib tdqm jupyter imageio fvcore plotly opencv-python 2. 下载对应pytorch3d版本：https://anaconda.org/pytorch3d/pytorch3d/files?page=10 我安装的版本：conda install pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2**

非常感谢您。根据这个回复我已经解决了问题。

**Comment by USTBcvpaperreading** [comment]
> 可以说一下是哪个文件报没有pytorch3d的吗？

是example_samples.py这个文件～
