### ISSUE TITLE
Downloading Pre-trained weights from Google Drive

### ISSUE THREAD

**Issue by Yacovitch** [QWTforGithub/PUDM#7]
Hi there,

First of all, thank you for sharing your awesome work on Git Hub. It is inspiring and impressive. I would like to conduct some experiments for my research with your pre-trained network. However, it seems like I need your permission to download the weights via Google Drive. Could you possibly give me the access?

**Comment by QWTforGithub** [comment]
> Hi there,
> 
> First of all, thank you for sharing your awesome work on Git Hub. It is inspiring and impressive. I would like to conduct some experiments for my research with your pre-trained network. However, it seems like I need your permission to download the weights via Google Drive. Could you possibly give me the access?

I'm so sorry, I overlooked this question. Please try the following link:
[https://drive.google.com/drive/folders/1XIgLSpAPmt_Zjn9SSBF4EWSCyiHF6ByZ?usp=sharing](url)
Is this link downloadable?

**Comment by Yacovitch** [comment]
It worked! Thank you very much!

**Comment by QWTforGithub** [comment]
> It worked! Thank you very much!

You are welcome!
